name: Release
on:
  push:
    tags:
      - v*

env:
  MIHON_GITHUB_RELEASE: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get_tag:
    if: github.repository == 'Saud-97/taihon'
    name: Extract tag name
    runs-on: 'ubuntu-24.04'
    outputs:
      tag: ${{ steps.extract.outputs.tag }}
      upstream: ${{ steps.extract.outputs.upstream }}
    steps:
      - name: Get tag name
        id: extract
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          UPSTREAM="${TAG%.*}"

          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "upstream=$UPSTREAM" >> "$GITHUB_OUTPUT"

  build:
    if: github.repository == 'Saud-97/taihon'
    name: Build
    runs-on: 'ubuntu-24.04'
    needs: get_tag

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up JDK
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          java-version-file: .github/.java-version
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Build
        run: ./gradlew assembleRelease -Pinclude-telemetry -Penable-updater
        env:
          storeFileBase64: ${{ secrets.SIGNING_KEY }}
          storePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyAlias: ${{ secrets.ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Rename APK
        run: |
          set -e

          mv app/build/outputs/apk/release/app-universal-release.apk taihon-${{ needs.get_tag.outputs.tag }}.apk
          mv app/build/outputs/apk/release/app-arm64-v8a-release.apk taihon-arm64-v8a-${{ needs.get_tag.outputs.tag }}.apk
          mv app/build/outputs/apk/release/app-armeabi-v7a-release.apk taihon-armeabi-v7a-${{ needs.get_tag.outputs.tag }}.apk
          mv app/build/outputs/apk/release/app-x86-release.apk taihon-x86-${{ needs.get_tag.outputs.tag }}.apk
          mv app/build/outputs/apk/release/app-x86_64-release.apk taihon-x86_64-${{ needs.get_tag.outputs.tag }}.apk

      - name: Upload APK
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: taihon
          path: |
            taihon-${{ needs.get_tag.outputs.tag }}.apk
            taihon-arm64-v8a-${{ needs.get_tag.outputs.tag }}.apk
            taihon-armeabi-v7a-${{ needs.get_tag.outputs.tag }}.apk
            taihon-x86-${{ needs.get_tag.outputs.tag }}.apk
            taihon-x86_64-${{ needs.get_tag.outputs.tag }}.apk

  build_foss:
    if: github.repository == 'Saud-97/taihon'
    name: Build (FOSS)
    runs-on: ubuntu-24.04
    needs: get_tag

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up JDK
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          java-version-file: .github/.java-version
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-disabled: true

      - name: Build
        run: ./gradlew assembleFoss -Penable-updater
        env:
          storeFileBase64: ${{ secrets.SIGNING_KEY }}
          storePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyAlias: ${{ secrets.ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Rename APK
        run: |
          set -e

          mv app/build/outputs/apk/foss/app-universal-foss.apk taihon-${{ needs.get_tag.outputs.tag }}-foss.apk

      - name: Upload APK
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: taihon-foss
          path: taihon-${{ needs.get_tag.outputs.tag }}-foss.apk

  release:
    if: github.repository == 'Saud-97/taihon'
    name: Create GitHub Release
    runs-on: ubuntu-24.04
    needs: [get_tag, build, build_foss]

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Find previous tag
        id: previous
        shell: bash
        run: |
          PREVIOUS_TAG=$(git tag --sort=-creatordate | sed -n '2p')

          echo "tag=$PREVIOUS_TAG" >> "$GITHUB_OUTPUT"

      - name: Generate changelog
        shell: bash
        run: |
          {
            echo "CHANGELOG<<EOF"
            git log \
              --no-merges \
              --pretty='* %s — @%an' \
              "${{ steps.previous.outputs.tag }}..${{ needs.get_tag.outputs.tag }}"
            echo EOF
          } >> "$GITHUB_ENV"

      - name: Download all artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          merge-multiple: true

      - name: Delete all artifacts
        uses: geekyeggo/delete-artifact@176a747ab7e287e3ff4787bf8a148716375ca118 # v6.0.0
        with:
          failOnError: false
          name: |
            taihon
            taihon-foss

      - name: Create GitHub Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          tag_name: ${{ needs.get_tag.outputs.tag }}
          name: Taihon ${{ needs.get_tag.outputs.tag }}
          body: |
            ${{ env.CHANGELOG }}

            ## 🔄 Upstream
            Updated with the latest changes from **Mihon ${{ needs.get_tag.outputs.upstream }}**.

            ## ✨ New Features

            ## ⚙️ Customizations

            ## 🚀 Improvements

            ## 🐛 Bug Fixes



            ---

            **Full Changelog**
            https://github.com/${{ github.repository }}/compare/${{ steps.previous.outputs.tag }}...${{ needs.get_tag.outputs.tag }}

            > [!TIP]
            >
            > If you are unsure which APK to download, use **`taihon-${{ needs.get_tag.outputs.tag }}.apk`**.
          files: |
            taihon-${{ needs.get_tag.outputs.tag }}.apk
            taihon-${{ needs.get_tag.outputs.tag }}-foss.apk
            taihon-arm64-v8a-${{ needs.get_tag.outputs.tag }}.apk
            taihon-armeabi-v7a-${{ needs.get_tag.outputs.tag }}.apk
            taihon-x86-${{ needs.get_tag.outputs.tag }}.apk
            taihon-x86_64-${{ needs.get_tag.outputs.tag }}.apk
          draft: true
          prerelease: false
          token: ${{ secrets.MIHON_BOT_TOKEN }}
